# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run maven verify on push or merge main branch

on:
  push:
    branches:
    - feature/*
    - ci/*
  pull_request:
    branches:
    - main
    types: [ closed ]

jobs:
  maven:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run verify
      run: mvn clean package verify
    - name: upload jar for next job
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: '${{ github.workspace }}/target/*.jar'

  docker:
    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Docker login
        run: docker login ghcr.io -u venclibalazs -p ${{ github.token }}
      - name: Docker build
        run: docker build . -t ghcr.io/venclibalazs/cubix/1/optional/app:springboot
      - name: Docker publish
        run: docker push ghcr.io/venclibalazs/cubix/1/optional/app:springboot
